package gui;

import java.text.DateFormat;

import domein.DomeinController;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;
import repository.BestellingDTO;
import repository.TransportdienstDTO;

public class BestellingenController extends Pane {
	private DomeinController dc;
	@FXML
	private TableView<BestellingDTO> tvBestellingen;
	@FXML
	TableColumn<BestellingDTO, String> orderColumn;
	@FXML
	TableColumn<BestellingDTO, String> statusColumn;
	@FXML
	TableColumn<BestellingDTO, String> klantColumn;
	@FXML
	TableColumn<BestellingDTO, String> transportdienstColumn;
	@FXML
	TableColumn<BestellingDTO, String> datumColumn;
	@FXML
	private Label lblDetailsBestelling;
	@FXML
	private Button btnWijzigBestelling;
	@FXML
	private Label txtDozenVoorVerpakking;
	@FXML
	private Label txtTransportDienst;
	@FXML
	private TextField txtNaamKlant;
	@FXML
	private TextField txtNaamAankoper;
	@FXML
	private TextField txtEmailAankoper;
	@FXML
	private TextField txtOrderId;
	@FXML
	private TextField txtDatumGeplaatst;
	@FXML
	private TextField txtLeveradres;
	@FXML
	private TextField txtStatus;
	@FXML
	private TextField txtTotaleOrderbedrag;
	@FXML
	private ComboBox<TransportdienstDTO> cmbTransportdienst;
	@FXML
	private TextField txtTrackTraceGegevens;
	//ToDo add ProductDTO
	@FXML
	private TableColumn productNaamColumn;
	@FXML
	private TableColumn productAantalColumn;
	@FXML
	private TableColumn productEenheidsprijsColumn;
	@FXML
	private TableColumn productTotalePrijsColumn;

	public BestellingenController() {

	}

	public void loadBestellingen() {
		System.out.println("Bestellingen");
		ObservableList<BestellingDTO> bestellingList = FXCollections.observableList(dc.getBestellingen());
		orderColumn.setCellValueFactory(cellData -> new SimpleStringProperty(cellData.getValue().getOrderID()));
		statusColumn.setCellValueFactory(cellData -> new SimpleStringProperty(cellData.getValue().getStatus()));
		klantColumn.setCellValueFactory(cellData -> new SimpleStringProperty(cellData.getValue().getKlantNaam()));
		transportdienstColumn.setCellValueFactory(
				cellData -> new SimpleStringProperty(cellData.getValue().getTransportdienstNaam()));
		datumColumn.setCellValueFactory(cellData -> new SimpleStringProperty(
				DateFormat.getDateInstance().format(cellData.getValue().getDatumGeplaatst())));
		tvBestellingen.setItems(bestellingList);

	}

	public void setParams(DomeinController dc) {

		this.dc = dc;
	}
	
	// Event Listener on Button[#btnWijzigBestelling].onAction
		@FXML
		public void wijzigBestelling(ActionEvent event) {
			// TODO Autogenerated
		}

}
